# Numpay
1. It is used for the  computation and processing single and multi-dimensional arrays of the elements
2. Smaller memory consumption and better runtime behaviour


In [2]:
!pip install numpy

In [3]:
import numpy as np

In [9]:
a = np.array([[1, 2, 3]])
print(a)

[[1 2 3]]


In [10]:
type(a)

numpy.ndarray

In [6]:
a = np.array([1, 2, 3] , dtype= float)
print(a)

[1. 2. 3.]


In [7]:
type(a)

numpy.ndarray

In [13]:
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=complex)
c = np.array([[1,2,4],[9,4,5]],dtype=complex)
d = np.array(c + b)

In [14]:
len(d)

2

In [15]:
print(d)

[[ 2.+0.j  4.+0.j  7.+0.j]
 [13.+0.j  9.+0.j 11.+0.j]]


In [21]:
e = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
print(e)

[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [ ]:
# Getting the shape of the array
print(e.shape)

(3, 1, 3)


In [23]:
# Getting the dimensions of the array
e.ndim

3

In [ ]:
# Why use the numpay ???
# 1. Efficient memory consumption 2. Fast processing speed 3. Convenient

In [ ]:
# Accessing / Changing specific elements, rows, columns, etc.
f = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])


np.int64(13)

In [25]:
#Getting the specific element 
f[1,5]

np.int64(13)

In [28]:
# Get the specific row from numpy array 
f[0,:]

array([24,  2,  3,  4,  5,  6,  7])

In [29]:
# Get the specific column from numpy array
f[:,2]

array([ 3, 10])

In [ ]:
# Chainging the specific element
f[0,0] = 24

In [27]:
print(f)

[[24  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
# Generating the array with zero and one method
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((3,3),dtype=complex)

array([[1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j]])

In [33]:
np.ones((2,3,4),dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [ ]:
# Full work as the creates a NumPy array of any shape and fills it with a specific value that you choose.
np.full((2,3,4),34 , dtype='int32')

array([[[34, 34, 34, 34],
        [34, 34, 34, 34],
        [34, 34, 34, 34]],

       [[34, 34, 34, 34],
        [34, 34, 34, 34],
        [34, 34, 34, 34]]], dtype=int32)

In [36]:
# using the random method 
np.random.rand(4,4)

array([[0.54818349, 0.46516979, 0.65955147, 0.43431451],
       [0.56847223, 0.04533164, 0.36056509, 0.949544  ],
       [0.75534175, 0.9690238 , 0.67123453, 0.89520991],
       [0.19196937, 0.72451823, 0.42943276, 0.92711507]])

In [41]:
np.random.randint(1,5,size=(3,3))

array([[4, 3, 3],
       [2, 3, 3],
       [4, 1, 3]], dtype=int32)

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])